# Choose the Image which has Node installed already
FROM $TF_VAR_ENV_APP_GL_DOCKER_REPOSITORY/node:18

# make the 'app' folder the current working directory
WORKDIR /app

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# install project dependencies
RUN npm install

EXPOSE ${TF_VAR_ENV_APP_BE_LOCAL_PORT}

CMD [ "npm", "start"]